///////////////////////////////
// Automatically generated code. Do not edit this file.
#pragma once 

namespace Proud
{
	/**
	\~korean
	에러 타입 코드

	\~english 
	Error type code.

	\~chinese
	错误类型代码。

	\~japanese
	エラータイプコード.
	\~
	*/
	enum class ErrorType: int
	{
			/**
		\~korean
		성공. 문제 없음.

		\~english 
		Success. No problem.

		\~chinese
		成功。没有问题。

		\~japanese
		成功。問題なし。
		\~
		*/
		Ok = 0,
			/**
		\~korean
		의도되지 않은 상황이 발생했습니다.

		\~english 
		Exception occurred.

		\~chinese
		发生例外情况。

		\~japanese
		例外状況発生。
		\~
		*/
		Unexpected = 1,
			/**
		\~korean
		이미 연결되어 있음.

		\~english 
		Already connected.

		\~chinese
		已经是连接状态。

		\~japanese
		既に接続されています。
		\~
		*/
		AlreadyConnected = 2,
			/**
		\~korean
		TCP 연결 실패

		\~english 
		TCP connection failed

		\~chinese
		TCP 连接失败。

		\~japanese
		TCP接続失敗
		\~
		*/
		TCPConnectFailure = 3,
			/**
		\~korean
		잘못된 대칭키

		\~english 
		Wrong matching key

		\~chinese
		错误的对称key。

		\~japanese
		間違った対称キー
		\~
		*/
		InvalidSessionKey = 4,
			/**
		\~korean
		암호화가 실패했음

		\~english 
		Encoding failed

		\~chinese
		加密失败。

		\~japanese
		暗号化が失敗しました。
		\~
		*/
		EncryptFail = 5,
			/**
		\~korean
		해커가 깨진 데이터를 전송했거나 복호화가 실패했음

		\~english 
		Either the hacker transmitted corrupt data or decoding failed.

		\~chinese
		黑客可能传送了乱码数据，或者是解码失败。

		\~japanese
		ハッカーが壊れたデータを転送したか復号化に失敗しました。
		\~
		*/
		DecryptFail = 6,
			/**
		\~korean
		서버 연결 과정이 너무 오래 걸려서 실패 처리됨

		\~english 
		Processed as failure since the server connection process took too much time.

		\~chinese
		因服务器连接时间过长而失败。

		\~japanese
		サーバー接続過程がとてもかかり過ぎて失敗処理になりました。
		\~
		*/
		ConnectServerTimeout = 7,
			/**
		\~korean
		서버 연결을 위한 프로토콜 버전이 다름

		\~english 
		Protocol version for server connection is different

		\~chinese
		服务器连接的网络协议版本不同。

		\~japanese
		サーバー接続のためのプロトコルバージョンが違います。
		\~
		*/
		ProtocolVersionMismatch = 8,
			/**
		\~korean
		서버 쪽 인증에 문제가 있음.

		\~english 
		Problem occured while license validation task.

		\~chinese
		Problem occured while license validation task.

		\~japanese
		Problem occured while license validation task.
		\~
		*/
		InvalidLicense = 9,
			/**
		\~korean
		서버가 연결을 의도적으로 거부했음

		\~english 
		Server intentionally rejected connection

		\~chinese
		服务器故意拒绝连接。

		\~japanese
		サーバーが接続を意図的に拒否しました。
		\~
		*/
		NotifyServerDeniedConnection = 10,
			/**
		\~korean
		서버 연결 성공!

		\~english 
		Server connection success!

		\~chinese
		服务器连接成功！

		\~japanese
		サーバー接続成功！
		\~
		*/
		Reserved01 = 11,
			/**
		\~korean
		상대측 호스트에서 연결을 해제했음

		\~english 
		The correspondent host removed the connection

		\~chinese
		对方主机解除了连接。

		\~japanese
		相手側のホストが接続を解除しました。
		\~
		*/
		DisconnectFromRemote = 12,
			/**
		\~korean
		이쪽 호스트에서 연결을 해제했음

		\~english 
		This side host removed the connection

		\~chinese
		这边主机解除了连接。

		\~japanese
		内側のホストが接続を解除しました。
		\~
		*/
		DisconnectFromLocal = 13,
			/**
		\~korean
		위험한 상황을 불러올 수 있는 인자가 있음

		\~english 
		There is a factor that can cause a dangerous situation

		\~chinese
		存在可能引起危险状况的因素。

		\~japanese
		危険な状況を引き起こす可能性のある因子があります。
		\~
		*/
		Reserved02 = 14,
			/**
		\~korean
		알 수 없는 인터넷 주소

		\~english 
		Unknown internet address

		\~chinese
		未知的互联网地址。

		\~japanese
		知られていないインターネットアドレス
		\~
		*/
		UnknownAddrPort = 15,
			/**
		\~korean
		서버 준비 부족

		\~english 
		Insufficient server readiness

		\~chinese
		服务器准备不足。

		\~japanese
		サーバー準備不足
		\~
		*/
		Reserved03 = 16,
			/**
		\~korean
		서버 소켓의 listen을 시작할 수 없습니다. TCP 또는 UDP 소켓이 이미 사용중인 포트인지 확인하십시오.

		\~english 
		You cannot start listen of the server socket. Please check whether either the TCP or UDP socket is a port already being used.

		\~chinese
		无法开始玩家socket的listen或者准备UDP。请确认TCP或者UDP socket端口是否已在使用中还是有限量在每个process的socket数量。

		\~japanese
		サーバーソケットのlistenを開始することができません。TCPまたはUDPソケットが既に使用中であるポートなのかを確認してください。
		\~
		*/
		ServerPortListenFailure = 17,
			/**
		\~korean
		이미 개체가 존재합니다.

		\~english 
		Already an object exists.

		\~chinese
		对象已存在。

		\~japanese
		既に個体が存在します。
		\~
		*/
		AlreadyExists = 18,
			/**
		\~korean
		접근이 거부되었습니다. <a target="_blank" href="http://guide.nettention.com/cpp_ko#dbc2_nonexclusive_overview" >비독점적 데이터 접근하기</a> 기능에서, DB cache server가 비독점적 접근 기능을 쓰지 않겠다는 설정이 되어 있으면 발생할 수 있습니다. 윈도우 비스타이상의 OS에서 관리자권한이 없이 CNetUtil::EnableTcpOffload( bool enable ) 함수가 호출되면 발생할 수 있습니다.

		\~english 
		Access denied. At <a target="_blank" href="http://guide.nettention.com/cpp_en#dbc2_nonexclusive_overview" >Accessing non-exclusive data</a> function, it could occur if a function that DB cache server does not use exclusive access function has been set. At OS over window vista, It could occur when CNetUtil::EnableTcpOffload( bool enable ) function is called without administration authority.

		\~chinese
		接近被拒绝。在<a target="_blank" href="http://guide.nettention.com/cpp_zh#dbc2_nonexclusive_overview" >访问共享性数据</a>%功能上，如果DB cache server被设置成不使用共享接近功能的话便会发生此状况。在window，vista 以上的OS中，没有管理员权限呼出 CNetUtil::EnableTcpOffload ( bool enable )函数的话，可能会发生此状况。

		\~japanese
		接近が拒否されました。<a target="_blank" href="http://guide.nettention.com/cpp_jp#dbc2_nonexclusive_overview" >Accessing non-exclusive data</a> 機能で, DB cache serverが非独占的接近機能を使用しないと設定されていると発生する可能性があります。Window Vista以上のOSで管理者権限なしに CNetUtil::EnableTcpOffload( bool enable ) 関数が呼び出されると発生する可能性があります。
		\~
		*/
		PermissionDenied = 19,
			/**
		\~korean
		잘못된 session Guid입니다.

		\~english 
		This is a wrong session Guid

		\~chinese
		错误的session Guid。

		\~japanese
		間違ったSession Guidです。
		\~
		*/
		BadSessionGuid = 20,
			/**
		\~korean
		잘못된 credential입니다.

		\~english 
		This is a wrong credential.

		\~chinese
		错误的credential。

		\~japanese
		間違ったCredentialです。
		\~
		*/
		InvalidCredential = 21,
			/**
		\~korean
		잘못된 hero name입니다.

		\~english 
		This is a wrong hero name.

		\~chinese
		错误的hero name。

		\~japanese
		間違ったHero nameです。
		\~
		*/
		InvalidHeroName = 22,
			/**
		\~korean
		로딩 과정이 unlock 후 lock 한 후 꼬임이 발생했다

		\~english 
		After the loading is locked after being unlocked, a problem occurred.

		\~chinese
		加载过程unlock以后，lock 后发生云集。

		\~japanese
		ローディング過程がアンロック後にロックし、ねじれが発生しました。
		\~
		*/
		Reserved06 = 23,
			/**
		\~korean
		출력 파라메터 AdjustedGamerIDNotFilled가 채워지지 않았습니다.

		\~english 
		The output parameter AdjustedGamerIDNotFilled has not been filled.

		\~chinese
		输出参数AdjustedGamerIDNotFilled没有被填充。

		\~japanese
		出力パラメーターのAdjustedGamerIDNotFilledが満たされていません。
		\~
		*/
		Reserved07 = 24,
			/**
		\~korean
		플레이어 캐릭터가 존재하지 않습니다.

		\~english 
		The player character does not exist.

		\~chinese
		玩家角色不存在。

		\~japanese
		プレーヤーキャラクターが存在しません。
		\~
		*/
		Reserved08 = 25,
			/**
		\~korean
		유닛 테스트 실패

		\~english 
		Unit test failed.

		\~chinese
		单元测试失败。

		\~japanese
		ユニットテスト失敗
		\~
		*/
		UnitTestFailed = 26,
			/**
		\~korean
		peer-to-peer UDP 통신이 막혔습니다.

		\~english 
		Peer-to-peer UDP communication is blocked.

		\~chinese
		peer-to-peer UDP 通信堵塞。

		\~japanese
		peer-to-peer UDP通信が詰まりました。
		\~
		*/
		P2PUdpFailed = 27,
			/**
		\~korean
		P2P reliable UDP가 실패했습니다.

		\~english 
		P2P reliable UDP failed.

		\~chinese
		P2P reliable UDP失败。

		\~japanese
		P2P reliable UDPが失敗しました。
		\~
		*/
		ReliableUdpFailed = 28,
			/**
		\~korean
		클라이언트-서버 UDP 통신이 막혔습니다.

		\~english 
		Client-server UDP communication is blocked.

		\~chinese
		玩家-服务器的UDP通信堵塞。

		\~japanese
		クライアントサーバーUDP通信が詰まりました。
		\~
		*/
		ServerUdpFailed = 29,
			/**
		\~korean
		더 이상 같이 소속된 P2P 그룹이 없습니다.

		\~english 
		There is no longer a P2P group that belongs together.

		\~chinese
		再没有一同所属的P2P组。

		\~japanese
		これ以上一緒に所属されたP2Pグループはありません。
		\~
		*/
		NoP2PGroupRelation = 30,
			/**
		\~korean
		사용자 정의 함수(RMI 수신 루틴 혹은 이벤트 핸들러)에서 exception이 throw되었습니다.

		\~english 
		An exception is thrown in the user defined function (an RMI receiving routine or an event handler).

		\~chinese
		从用户定义函数（RMI 收信例程或者事件handler）exception 被throw。

		\~japanese
		ユーザー定義関数(RMI受信ルーチンまたはイベントハンドラー)でexceptionがthrowされました。
		\~
		*/
		ExceptionFromUserFunction = 31,
			/**
		\~korean
		사용자의 요청에 의한 실패입니다.

		\~english 
		This is a failure due to a user request.

		\~chinese
		用户邀请造成的失败。

		\~japanese
		ユーザーの要請による失敗です。
		\~
		*/
		UserRequested = 32,
			/**
		\~korean
		잘못된 패킷 형식입니다. 상대측 호스트가 해킹되었거나 버그일 수 있습니다.

		\~english 
		This is a wrong packet type. Either the correspondent host is hacked or it is a bug.

		\~chinese
		错误的数据包形式。可能是对方主机被黑或者是存在漏洞。

		\~japanese
		間違ったパケット形式です。相手側のホストがハッキングされたか、バグである可能性があります。
		\~
		*/
		InvalidPacketFormat = 33,
			/**
		\~korean
		너무 큰 크기의 메시징이 시도되었습니다. 기술지원부에 문의하십시오. 필요시 <a target="_blank" href="http://guide.nettention.com/cpp_ko#message_length" >통신 메시지의 크기 제한</a>  를 참고하십시오.

		\~english 
		A messaging with too big size has been attempted. Please contact the technical support team. If necessary, refer to \ref message_length

		\~chinese
		试图使用了过大的messaging。请咨询技术支援部。必要时请参考<a target="_blank" href="http://guide.nettention.com/cpp_zh#message_length" >限制通信信息大小</a>%。

		\~japanese
		あまりにも大きいサイズのメッセージングが試されました。技術支援部までお問合せください。必要によって、\ref message_lengthをご参照ください。
		\~
		*/
		TooLargeMessageDetected = 34,
			/**
		\~korean
		websocket 메세지는 encrypt 할수 없습니다.

		\~english 
		You cannot encrypt an websocket message.

		\~chinese
		websocket 信息不能encrypt。

		\~japanese
		websocketメッセージはencryptできません。
		\~
		*/
		NoNeedWebSocketEncryption = 35,
			/**
		\~korean
		존재하지 않는 값입니다.

		\~english 
		This value does not exist

		\~chinese
		不存在的值。

		\~japanese
		存在しない値です。
		\~
		*/
		ValueNotExist = 36,
			/**
		\~korean
		타임아웃 입니다.

		\~english 
		This is a time-out.

		\~chinese
		超时。

		\~japanese
		タイムアウトです。
		\~
		*/
		TimeOut = 37,
			/**
		\~korean
		로드된 데이터를 찾을수 없습니다.

		\~english 
		The loaded data cannot be located.

		\~chinese
		无法找到加载的数据。

		\~japanese
		ロードされたデータが見つかりません。
		\~
		*/
		LoadedDataNotFound = 38,
			/**
		\~korean
		<a target="_blank" href="http://guide.nettention.com/cpp_ko#send_queue_heavy" >송신량 과다시 경고 발생 기능</a>. 송신 queue가 지나치게 커졌습니다.

		\~english 
		<a target="_blank" href="http://guide.nettention.com/cpp_en#send_queue_heavy" >Warning function for traffic overload</a> \ref send_queue_heavy. Transmission queue became too big.

		\~chinese
		<a target="_blank" href="http://guide.nettention.com/cpp_zh#send_queue_heavy" >送信量过多时发生警告的功能</a>。传送queue过大。

		\~japanese
		\ref send_queue_heavy . 送信キューがあまりにも大き過ぎです。
		\~
		*/
		SendQueueIsHeavy = 39,
			/**
		\~korean
		Heartbeat가 평균적으로 너무 느림

		\~english 
		The heartbeat is too slow on average.

		\~chinese
		Heartbeat 平均太慢。

		\~japanese
		Heartbeatが平均的にとても遅いです。
		\~
		*/
		TooSlowHeartbeatWarning = 40,
			/**
		\~korean
		메시지 압축이 실패 하였습니다.

		\~english 
		The message compression has failed.

		\~chinese
		信息压缩失败。

		\~japanese
		メッセージ圧縮に失敗しました。
		\~
		*/
		CompressFail = 41,
			/**
		\~korean
		클라이언트 소켓의 listen 혹은 UDP 준비를 할 수 없습니다. TCP 또는 UDP 소켓이 이미 사용중인 포트인지, 프로세스당 소켓 갯수 제한이 있는지 확인하십시오.

		\~english 
		Unable to listen client socket or prepare UDP. Must check if there is limitation in number of socket per process or if either TCP or UDP socket is already in use.

		\~chinese
		无法开始玩家socket的listen或者准备UDP。请确认TCP或者UDP socket端口是否已在使用中还是有限量在每个process的socket数量。

		\~japanese
		クライアントソケットのlistenを開始することができません。TCPまたはUDPソケットが既に使用中であるポートなのかをご確認ください。
		\~
		*/
		LocalSocketCreationFailed = 42,
			/**
		\~korean
		Socket을 생성할 때 Port Pool 내 port number로의 bind가 실패했습니다. 대신 임의의 port number가 사용되었습니다. Port Pool의 갯수가 충분한지 확인하십시요.

		\~english 
		Failed binding to local port that defined in Port Pool. Please check number of values in Port Pool are sufficient.

		\~chinese
		生成socket的时候往Port Pool内port number的bind失败。任意port number被代替使用。请确认Port Pool的个数是否充分。

		\~japanese
		Socketを生成する時、Port Pool内のPort Numberへのバインドに失敗しました。代わりに任意のPort Numberが使われました。Port Poolの数が十分なのかをご確認ください。
		\~
		*/
		NoneAvailableInPortPool = 43,
			/**
		\~korean
		Port pool 내 값들 중 하나 이상이 잘못되었습니다. 포트를 0(임의 포트 바인딩)으로 하거나 중복되지 않았는지 확인하십시요.

		\~english 
		Range of user defined port is wrong. Set port to 0(random port binding) or check if it is overlaped.

		\~chinese
		Port pool 中一个以上的内值出错。确认把端口设为0（任意端口binding）或者是否重复。

		\~japanese
		Port pool内の値のうち一つ以上が間違っています。ポートを0(任意ポートバインディング)にするか重複されていないかをご確認ください。
		\~
		*/
		InvalidPortPool = 44,
			/**
		\~korean
		유효하지 않은 HostID 값입니다.

		\~english 
		Invalid HostID.

		\~chinese
		无效的HostID。

		\~japanese
		有効ではないHostID値です。
		\~
		*/
		InvalidHostID = 45,
			/**
		\~korean
		사용자가 소화하는 메시지 처리 속도보다 내부적으로 쌓이는 메시지의 속도가 더 높습니다. 지나치게 너무 많은 메시지를 송신하려고 했는지, 혹은 사용자의 메시지 수신 함수가 지나치게 느리게 작동하고 있는지 확인하십시오.

		\~english 
		The speed of stacking messages are higher than the speed of processing them. Check that you are sending too many messages, or your message processing routines are running too slowly.

		\~chinese
		消息的堆叠速度高于处理它们的速度。检查您要发送的邮件太多，或消息处理程序运行过慢。

		\~japanese
		ユーザーが消化するメッセージ処理速度より内部的に積もるメッセージの速度がもっと速いです。あまりにも多過ぎるメッセージを送信しようとしていないか、またはユーザーのメッセージ受信関数があまりにも遅く作動してはいないかを確認してください。
		\~
		*/
		MessageOverload = 46,
			/**
		\~korean
		Accessing database failed. For example, query statement execution failed. You may see the details from comment variable.

		\~english 
		Accessing database failed. For example, query statement execution failed. You may see the details from comment variable.

		\~chinese
		Accessing database failed. For example, query statement execution failed. You may see the details from comment variable.

		\~japanese
		Accessing database failed. For example, query statement execution failed. You may see the details from comment variable.
		\~
		*/
		DatabaseAccessFailed = 47,
			/**
		\~korean
		메모리가 부족합니다.

		\~english 
		Out of memory.

		\~chinese
		内存不足.

		\~japanese
		メモリーが足りません。
		\~
		*/
		OutOfMemory = 48,
			/**
		\~korean
		서버와의 연결이 끊어져서 연결 복구 기능이 가동되었지만, 이것 마저도 실패했습니다.

		\~english 
		서버와의 연결이 끊어져서 연결 복구 기능이 가동되었지만, 이것 마저도 실패했습니다.

		\~chinese
		서버와의 연결이 끊어져서 연결 복구 기능이 가동되었지만, 이것 마저도 실패했습니다.

		\~japanese
		서버와의 연결이 끊어져서 연결 복구 기능이 가동되었지만, 이것 마저도 실패했습니다.
		\~
		*/
		AutoConnectionRecoveryFailed = 49,
			/**
		\~korean
		RMI 함수를 호출 했지만, 함수 구현부가 없습니다.

		\~english 
		RMI 함수를 호출 했지만, 함수 구현부가 없습니다.

		\~chinese
		RMI 함수를 호출 했지만, 함수 구현부가 없습니다.

		\~japanese
		RMI 함수를 호출 했지만, 함수 구현부가 없습니다.
		\~
		*/
		NotImplementedRmi = 50,
		};

	// 하위 호환성 혹은 프라우드넷 내부에서 사용합니다.
		#define ErrorType_Ok (ErrorType::Ok) 
		#define ErrorType_Unexpected (ErrorType::Unexpected) 
		#define ErrorType_AlreadyConnected (ErrorType::AlreadyConnected) 
		#define ErrorType_TCPConnectFailure (ErrorType::TCPConnectFailure) 
		#define ErrorType_InvalidSessionKey (ErrorType::InvalidSessionKey) 
		#define ErrorType_EncryptFail (ErrorType::EncryptFail) 
		#define ErrorType_DecryptFail (ErrorType::DecryptFail) 
		#define ErrorType_ConnectServerTimeout (ErrorType::ConnectServerTimeout) 
		#define ErrorType_ProtocolVersionMismatch (ErrorType::ProtocolVersionMismatch) 
		#define ErrorType_InvalidLicense (ErrorType::InvalidLicense) 
		#define ErrorType_NotifyServerDeniedConnection (ErrorType::NotifyServerDeniedConnection) 
		#define ErrorType_Reserved01 (ErrorType::Reserved01) 
		#define ErrorType_DisconnectFromRemote (ErrorType::DisconnectFromRemote) 
		#define ErrorType_DisconnectFromLocal (ErrorType::DisconnectFromLocal) 
		#define ErrorType_Reserved02 (ErrorType::Reserved02) 
		#define ErrorType_UnknownAddrPort (ErrorType::UnknownAddrPort) 
		#define ErrorType_Reserved03 (ErrorType::Reserved03) 
		#define ErrorType_ServerPortListenFailure (ErrorType::ServerPortListenFailure) 
		#define ErrorType_AlreadyExists (ErrorType::AlreadyExists) 
		#define ErrorType_PermissionDenied (ErrorType::PermissionDenied) 
		#define ErrorType_BadSessionGuid (ErrorType::BadSessionGuid) 
		#define ErrorType_InvalidCredential (ErrorType::InvalidCredential) 
		#define ErrorType_InvalidHeroName (ErrorType::InvalidHeroName) 
		#define ErrorType_Reserved06 (ErrorType::Reserved06) 
		#define ErrorType_Reserved07 (ErrorType::Reserved07) 
		#define ErrorType_Reserved08 (ErrorType::Reserved08) 
		#define ErrorType_UnitTestFailed (ErrorType::UnitTestFailed) 
		#define ErrorType_P2PUdpFailed (ErrorType::P2PUdpFailed) 
		#define ErrorType_ReliableUdpFailed (ErrorType::ReliableUdpFailed) 
		#define ErrorType_ServerUdpFailed (ErrorType::ServerUdpFailed) 
		#define ErrorType_NoP2PGroupRelation (ErrorType::NoP2PGroupRelation) 
		#define ErrorType_ExceptionFromUserFunction (ErrorType::ExceptionFromUserFunction) 
		#define ErrorType_UserRequested (ErrorType::UserRequested) 
		#define ErrorType_InvalidPacketFormat (ErrorType::InvalidPacketFormat) 
		#define ErrorType_TooLargeMessageDetected (ErrorType::TooLargeMessageDetected) 
		#define ErrorType_NoNeedWebSocketEncryption (ErrorType::NoNeedWebSocketEncryption) 
		#define ErrorType_ValueNotExist (ErrorType::ValueNotExist) 
		#define ErrorType_TimeOut (ErrorType::TimeOut) 
		#define ErrorType_LoadedDataNotFound (ErrorType::LoadedDataNotFound) 
		#define ErrorType_SendQueueIsHeavy (ErrorType::SendQueueIsHeavy) 
		#define ErrorType_TooSlowHeartbeatWarning (ErrorType::TooSlowHeartbeatWarning) 
		#define ErrorType_CompressFail (ErrorType::CompressFail) 
		#define ErrorType_LocalSocketCreationFailed (ErrorType::LocalSocketCreationFailed) 
		#define ErrorType_NoneAvailableInPortPool (ErrorType::NoneAvailableInPortPool) 
		#define ErrorType_InvalidPortPool (ErrorType::InvalidPortPool) 
		#define ErrorType_InvalidHostID (ErrorType::InvalidHostID) 
		#define ErrorType_MessageOverload (ErrorType::MessageOverload) 
		#define ErrorType_DatabaseAccessFailed (ErrorType::DatabaseAccessFailed) 
		#define ErrorType_OutOfMemory (ErrorType::OutOfMemory) 
		#define ErrorType_AutoConnectionRecoveryFailed (ErrorType::AutoConnectionRecoveryFailed) 
		#define ErrorType_NotImplementedRmi (ErrorType::NotImplementedRmi) 
	}